# Generated by Django 6.0.3 on 2026-03-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_alter_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
